name: Publish Docker Image

on:
  push:
    branches:
    - 'feature/**'

jobs:

  build:
    env:
      RUNNER_DIR: '/home/runner/work/docker-image-builder/docker-image-builder'
      BRANCH_NAME: $(echo $GITHUB_REF | sed "s/refs\/heads\/feature\///g")
      BUILD_VERSION: '1.0'
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: | 
        docker build ${RUNNER_DIR} --file Dockerfile --tag ghcr.io/mertcarabaci/${BRANCH_NAME}:${BUILD_VERSION}
        docker push ghcr.io/mertcarabaci/${BRANCH_NAME}:${BUILD_VERSION}
