name: Publish Docker Image

on:
  push:
    branches:
      - 'feature/**'
  

jobs:

  build:
    env:
      RUNNER_DIR: '/home/runner/work/docker-image-builder/docker-image-builder'
      BRANCH_NAME: '$(echo $GITHUB_REF | sed "s/refs\/heads\/feature\///g")'
      BUILD_VERSION: 'v1.0'
      
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        echo $(bash ./.github/workflows/tag.bash)
        echo $BUILD_VERSION
        echo "BUILD_ID=${BUILD_VERSION}-$(bash ./.github/workflows/tag.bash)" >> $GITHUB_ENV
         
        echo $BUILD_ID

    - name: Authenticate to Google Cloud
      run: |
        echo $BUILD_ID

    - name: Tag
      run: |
        tag=$BUILD_ID
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git tag -a "${tag}" -m "new tag"
        git push origin "${tag}"


