name: Publish Docker Image

on:
  push:
    branches:
      - 'feature/**'
  

jobs:

  build:
    env:
      RUNNER_DIR: '/home/runner/work/docker-image-builder/docker-image-builder'
      BRANCH_NAME: '$(echo $GITHUB_REF | sed "s/refs\/heads\/feature\///g")'
      BUILD_VERSION: '1.0'
      
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}'
      - name: Building and pushing the image
        uses: RafikFarhad/push-to-gcr-github-action@v5-rc1 # <- use this on your workflow
        with:
          # gcloud_service_key: ${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }} # <- not needed when used with google-github-actions/auth@v2
          registry: gcr.io
          project_id: mert-personal
          image_name: database-api
          image_tag: test-${{ github.sha }}, ${{ github.sha }}
          dockerfile: ./Dockerfile
          context: .
          target: build

