name: Publish Docker Image

on:
  push:
    branches:
      - 'feature/**'
  

jobs:

  build:
    env:
      RUNNER_DIR: '/home/runner/work/docker-image-builder/docker-image-builder'
      BRANCH_NAME: '$(echo $GITHUB_REF | sed "s/refs\/heads\/feature\///g")'
      BUILD_VERSION: 'v1.0'
      
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Build the Docker image
      run: | 
        echo $(bash ./.github/workflows/tag.bash)
        echo $BUILD_VERSION
        BUILD_VERSION="${BUILD_VERSION}-$(bash ./.github/workflows/tag.bash)"
        echo $BUILD_VERSION

    - name: Authenticate to Google Cloud
      run: |
        echo $BUILD_VERSION 
    - name: Pushing the image
      uses: RafikFarhad/push-to-gcr-github-action@v5-rc1 # <- use this on your workflow
      with:
        registry: gcr.io
        project_id: mert-personal
        image_name: database-api2
        image_tag: ${{ github.sha }}
        push_only: true
